//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.20 at 07:43:59 PM MEZ 
//

package de.janbusch.jhashpassword.xml.simple;

import java.io.Serializable;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

/**
 * <p>
 * Java class for Host complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Host">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoginNames" type="{hp:HashPassword}LoginNames"/>
 *       &lt;/sequence>
 *       &lt;attribute name="HashType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Charset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PasswordLength" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LastLogin" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Root
public class Host implements Serializable {

	/**
	 * SerialVersionUID
	 */
	private static final long serialVersionUID = 835162640093074986L;
	
	@Attribute(name = "HashType", required = true)
	private String hashType;
	@Attribute(name = "Charset", required = true)
	private String charset;
	@Attribute(name = "PasswordLength", required = true)
	private String passwordLength;
	@Attribute(name = "LastLogin", required = false)
	private String lastLogin;
	@Attribute(name = "Name", required = true)
	private String name;
	@Element(name = "LoginNames", required = false)
	private LoginNames loginNames;

	/**
	 * Gets the value of the loginNames property.
	 * 
	 * @return possible object is {@link LoginNames }
	 * 
	 */
	public LoginNames getLoginNames() {
		if (loginNames == null) {
			loginNames = new LoginNames();
		}
		return loginNames;
	}

	/**
	 * Sets the value of the loginNames property.
	 * 
	 * @param value
	 *            allowed object is {@link LoginNames }
	 * 
	 */
	public void setLoginNames(LoginNames value) {
		this.loginNames = value;
	}

	/**
	 * Gets the value of the hashType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHashType() {
		return hashType;
	}

	/**
	 * Sets the value of the hashType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHashType(String value) {
		this.hashType = value;
	}

	/**
	 * Gets the value of the charset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCharset() {
		return charset;
	}

	/**
	 * Sets the value of the charset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCharset(String value) {
		this.charset = value;
	}

	/**
	 * Gets the value of the passwordLength property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPasswordLength() {
		return passwordLength;
	}

	/**
	 * Sets the value of the passwordLength property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPasswordLength(String value) {
		this.passwordLength = value;
	}

	/**
	 * Gets the value of the lastLogin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLastLogin() {
		if (lastLogin == null) {
			lastLogin = "";
		}
		return lastLogin;
	}

	/**
	 * Sets the value of the lastLogin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLastLogin(String value) {
		this.lastLogin = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
