//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.20 at 07:43:59 PM MEZ 
//

package de.janbusch.jhashpassword.xml.simple;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.ElementList;

/**
 * <p>
 * Java class for Hosts complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Hosts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Host" type="{hp:HashPassword}Host" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Count" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Hosts implements Serializable {

	/**
	 *  SerialVersionUID
	 */
	private static final long serialVersionUID = 8241188186830328397L;
	
	@ElementList(entry = "Host", inline = true, required = false)
	private List<Host> host;
	@Attribute(name = "Count", required = false)
	private BigInteger count;

	/**
	 * Gets the value of the host property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the host property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getHost().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Host }
	 * 
	 * 
	 */
	public List<Host> getHost() {
		if (host == null) {
			host = new ArrayList<Host>();
		}
		return this.host;
	}

	public Host getHostByName(String hostName) {
		if (host == null) {
			host = new ArrayList<Host>();
		}

		for (Host host : this.host) {
			if (host.getName().equals(hostName)) {
				return host;
			}
		}

		return null;
	}

	/**
	 * Gets the value of the count property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getCount() {
		return count;
	}

	/**
	 * Sets the value of the count property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setCount(BigInteger value) {
		this.count = value;
	}

}
