//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.20 at 07:43:59 PM MEZ 
//

package de.janbusch.jhashpassword.xml.simple;

import java.io.Serializable;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Root;

/**
 * <p>
 * Java class for LoginName complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="LoginName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Root
public class LoginName implements Serializable, Comparable<LoginName> {

	/**
	 * SerialVersionUID
	 */
	private static final long serialVersionUID = -4550235628526155604L;

	@Attribute(name = "Name", required = true)
	private String name;
	@Attribute(name = "HashType", required = false)
	private String hashType;
	@Attribute(name = "Charset", required = false)
	private String charset;
	@Attribute(name = "PasswordLength", required = false)
	private String passwordLength;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the hashType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHashType() {
		return hashType;
	}

	/**
	 * Sets the value of the hashType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHashType(String value) {
		this.hashType = value;
	}

	/**
	 * Gets the value of the charset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCharset() {
		return charset;
	}

	/**
	 * Sets the value of the charset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCharset(String value) {
		this.charset = value;
	}

	/**
	 * Gets the value of the passwordLength property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPasswordLength() {
		return passwordLength;
	}

	/**
	 * Sets the value of the passwordLength property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPasswordLength(String value) {
		this.passwordLength = value;
	}

	@Override
	public int compareTo(LoginName o) {
		return this.name.compareTo(o.getName());
	}

}
